package com.honeycomb.demo.entity.dao;

import com.honeycomb.demo.entity.po.DemoAccount;
import com.honeycomb.demo.entity.po.DemoAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DemoAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    long countByExample(DemoAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int deleteByExample(DemoAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int insert(DemoAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int insertSelective(DemoAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    DemoAccount selectOneByExample(DemoAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    DemoAccount selectOneByExampleSelective(@Param("example") DemoAccountExample example, @Param("selective") DemoAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    List<DemoAccount> selectByExampleSelective(@Param("example") DemoAccountExample example, @Param("selective") DemoAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    List<DemoAccount> selectByExample(DemoAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    DemoAccount selectByPrimaryKeySelective(@Param("accountId") Integer accountId, @Param("selective") DemoAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    DemoAccount selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DemoAccount record, @Param("example") DemoAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DemoAccount record, @Param("example") DemoAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DemoAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DemoAccount record);
}